### ISSUE TITLE
Basic Documentation Please

### ISSUE THREAD

**Issue by EisenbergEffect** [jasonwarford/aurelia-atom-shell#1]
I'd love to see some simple documentation here. I downloaded the zip, npm and jspm installed...then wasn't sure what to do next. Perhaps just a short list of steps to go through to get the build set up and run the app.

**Comment by zewa666** [comment]
+1 on that

**Comment by jasonwarford** [comment]
I'll get that updated this weekend.

**Comment by jasonwarford** [comment]
I've updated the documentation. Hope that helps.
